rfid/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import views

app_name = 'rfid'
urlpatterns = [
                  path('', views.IndexView.as_view(), name='index'),

                  path('add_card/', views.add_card, name='add_card'),
                  path('add_card_scan/', views.AddCardScanView.as_view(), name='add_card_scan'),

                  path('write_card/', views.write_card, name='write_card'),
                  path('write_card_scan/', views.WriteCardScanView.as_view(), name='write_card_scan'),

                  path('info_card/', views.info_card, name='info_card'),
                  path('info_card_scan/', views.InfoCardScanView.as_view(), name='info_card_scan'),

                  path('delete_card/', views.delete_card, name='delete_card'),
                  path('delete_card_scan/', views.DeleteCardScanView.as_view(), name='delete_card_scan'),

                  path('dashboard/', views.dashboard, name='dashboard'),
                  path('logs', views.logs, name='logs'),

                  path('about/', views.AboutView.as_view(), name='about'),

                  path('access/', views.AccessMainView.as_view(), name='access_main'),
                  path('access/result/', views.access_result, name='access_result'),
                  path('access/result/<int:card_id>/', views.access_result, name='access_result'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartaccess/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('rfid/', include('rfid.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='rfid/'), name='index_redir'),

]

rfid/models.py
from django.db import models
from django.utils import timezone


# The primary-key is the card id
class RFIDCard(models.Model):
    card_id = models.IntegerField(primary_key=True)
    remaining_accesses = models.IntegerField(default=0)
    expiration_date = models.DateField(default=timezone.datetime.now)

    def __str__(self):
        return "Id: {}, remaining accesses: {}, expiration date: {}".format(self.card_id, self.remaining_accesses,
                                                                            self.expiration_date)


class Log(models.Model):
    id = models.AutoField(primary_key=True)
    card = models.ForeignKey(RFIDCard, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to="{}.jpg".format(id), null=True)
    log_datetime = models.DateTimeField(default=timezone.datetime.now)
    age = models.IntegerField(null=True)
    sex = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')), null=True)

    def __str__(self):
        return 'Id: {}, card: {}, time: {}'.format(self.id, self.card, self.log_datetime)

rfid/forms.py
from django import forms
from django.utils import timezone
import datetime

from .models import RFIDCard


class WriteCardForm(forms.ModelForm):

    def clean(self):
        # To keep the main validation and error messages
        cleaned_data = super(WriteCardForm, self).clean()

        card_id = self.cleaned_data['card_id']
        if not RFIDCard.objects.filter(pk=card_id).exists():
            self.add_error('card_id', "Card not registered, please add it to the database first")

        if cleaned_data['remaining_accesses'] < 0:
            self.add_error('remaining_accesses', "Value must be greater or equal than 0")

        if cleaned_data['expiration_date'] < datetime.date.today():
            self.add_error('expiration_date', "Date can't be in the past")

        return cleaned_data

    class Meta:
        model = RFIDCard
        fields = ["card_id", "remaining_accesses", "expiration_date"]
        widgets = {
            "card_id": forms.TextInput(attrs={'readonly': True, 'blank': True}),
            "expiration_date": forms.DateInput(attrs={'class': 'datepicker', 'id': 'datepicker'})
        }
        help_texts = {
            "remaining_accesses": "0 won't change the number of remaining accesses.",
            "expiration_date": "The date shown initially is the current expiration date."
                               " A date earlier than the current one won't modify the expiration date."
        }
        labels = {
            "remaining_accesses": "Accesses to add"
        }

rfid/views.py
from django.forms import Form
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.utils import timezone
from django.views.generic import TemplateView
from .models import RFIDCard, Log
from .forms import WriteCardForm
# import mfrc522
# from RPLCD import CharLCD
import datetime
import json
import RPi.GPIO as GPIO

from rfid.programs import face_detect, RFIDSingleton
from rfid.programs.RFIDSingleton import RFIDSingleton


def clear_session_var(request):
    try:
        request.session.pop('card_id')
    except KeyError:
        pass


class IndexView(TemplateView):
    template_name = 'rfid/index.html'

    def setup(self, request, *args, **kwargs):
        # Delete cache before new operations
        clear_session_var(request)

        return super().setup(request, *args, **kwargs)


class AddCardScanView(TemplateView):
    template_name = 'rfid/add_card_scan.html'


class WriteCardScanView(TemplateView):
    template_name = 'rfid/write_card_scan.html'


class InfoCardScanView(TemplateView):
    template_name = 'rfid/info_card_scan.html'


class DeleteCardScanView(TemplateView):
    template_name = 'rfid/delete_card_scan.html'


# Displays the page waiting for the card, which redirect to the access view
class AccessMainView(TemplateView):
    template_name = 'rfid/access_main.html'


class AboutView(TemplateView):
    template_name = 'rfid/about.html'


def add_card(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must authenticate before adding a card', extra_tags='alert-danger')
        return redirect('%s?next=%s' % (reverse('login'), reverse('rfid:add_card_scan')))

    try:
        card_id = request.session.pop('card_id')
    except KeyError:
        reader = RFIDSingleton()
        reader.set_reading(True)
        card_id = reader.read_id()
        reader.set_reading(False)
        # card_id = input('Type card id')

    if RFIDCard.objects.filter(card_id=card_id).exists():
        return render(request, 'rfid/add_card_fail.html', context={'card_id': card_id})

    new_card = RFIDCard(card_id=card_id)
    new_card.save()
    request.session['card_id'] = card_id
    return render(request, 'rfid/add_card_success.html', context={'card_id': card_id})


def write_card(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must authenticate before writing on a card', extra_tags='alert-danger')
        return redirect('%s?next=%s' % (reverse('login'), reverse('rfid:write_card_scan')))
    # messages.info(request, 'Scan the card you want to write on')

    # check if the card has been scanned before
    try:
        card_id = request.session.pop('card_id')
    except KeyError:
        reader = RFIDSingleton()
        reader.set_reading(True)
        card_id = reader.read_id()
        reader.set_reading(False)
        # TODO remember to revert to read_id() function
        # card_id = '5279589593186'
        # card_id = input('Type card id')

    try:
        card = RFIDCard.objects.get(pk=card_id)
        old_remaining_accesses = card.remaining_accesses
        old_expiration_date = card.expiration_date

        if request.method == 'POST':
            # RFIDCard model bound form
            form = WriteCardForm(request.POST, instance=card, initial={"expiration_date": card.expiration_date})
            if form.is_valid():
                # Validation is done at form level in the clean() method override

                card.remaining_accesses += old_remaining_accesses
                if form.cleaned_data["expiration_date"] > old_expiration_date:
                    card.expiration_date = form.cleaned_data["expiration_date"]
                else:
                    card.expiration_date = old_expiration_date
                card.save()

                return render(request, 'rfid/write_card_success.html', context={'card_id': card_id,
                                                                                'remaining_accesses': card.remaining_accesses,
                                                                                'expiration_date': card.expiration_date})
        else:
            # unbound form
            form = WriteCardForm(initial={'card_id': card_id,
                                          'expiration_date': card.expiration_date})

        request.session['card_id'] = card_id
        return render(request, 'rfid/write_card.html', {'form': form})

    except RFIDCard.DoesNotExist:
        request.session['card_id'] = card_id
        return render(request, 'rfid/write_card_add_new.html', context={'card_id': card_id})


def info_card(request):
    reader = RFIDSingleton()
    reader.set_reading(True)
    card_id = reader.read_id()
    reader.set_reading(False)
    # card_id = input('Type card id')
    if RFIDCard.objects.filter(card_id=card_id).exists():
        card = RFIDCard.objects.get(card_id=card_id)
        context = {'card_id': card.card_id,
                   'remaining_accesses': card.remaining_accesses,
                   'expiration_date': card.expiration_date}
    else:
        context = {'card_id': card_id}
        messages.warning(request, 'Your card is not registered', extra_tags='alert-warning')
    return render(request, 'rfid/info_card.html', context=context)


def delete_card(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must authenticate before deleting a card', extra_tags='alert-danger')
        return redirect('%s?next=%s' % (reverse('login'), reverse('rfid:delete_card_scan')))

    try:
        card_id = request.session.pop('card_id')
    except KeyError:
        reader = RFIDSingleton()
        reader.set_reading(True)
        card_id = reader.read_id()
        reader.set_reading(False)
        # TODO remember to revert to read_id() function
        # card_id = '5279589593186'
        # card_id = input('Type card id')

    if RFIDCard.objects.filter(card_id=card_id).exists():
        card = RFIDCard.objects.get(card_id=card_id)
        form = Form()
        context = {'card_id': card.card_id,
                   'remaining_accesses': card.remaining_accesses,
                   'expiration_date': card.expiration_date,
                   'form': form}
        # FIXME redirected to delete_card after submit
        if request.method == 'POST':
            card.delete()
            messages.success(request, 'The card {} has been deleted'.format(card_id), extra_tags='alert-success')
            return render(request, 'rfid/delete_card_scan.html', context=context)
        else:
            request.session['card_id'] = card_id
            return render(request, 'rfid/delete_card.html', context=context)
    else:
        context = {'card_id': card_id}
        messages.warning(request, 'Your card is not registered', extra_tags='alert-warning')
        return render(request, 'rfid/delete_card_scan.html', context=context)


# card_id is eventually passed from the URL (see rfid/urls.py)
def access_result(request, card_id=None):

    if card_id is None:
        try:
            reader = RFIDSingleton()
            reader.set_reading(True)
            card_id = reader.read_id()
            reader.set_reading(False)
        except:
            print("Exception")
        # card_id = input('Type card id')
    # lcd = CharLCD(cols=16, rows=2, pin_rs=37, pin_e=35, pins_data=[40, 38, 36, 32, 33, 31, 29, 23])
    # lcd.write_string(u'Scan your card')
    try:
        if RFIDCard.objects.get(card_id=card_id):
            card = RFIDCard.objects.get(card_id=card_id)
            if card.remaining_accesses > 0 and card.expiration_date >= datetime.date.today():
                card.remaining_accesses -= 1
                GPIO.output(18, GPIO.HIGH)

                # log_data = face_detect.get_photo_data(Log.objects.latest('id').id+1)
                # log_data['card'] = card
                # log_data['log_datetime'] = timezone.now()

                # TODO Code to add when you want to take a photo with the Raspberry (Part 1)
                new_log = Log(card=card, log_datetime=timezone.datetime.now())

                # new_log = Log(**log_data)
                card.save()
                new_log.save()

                # TODO Code to add when you want to take a photo with the Raspberry (Part 2)
                # new_log is saved two times because before the first save it does not have id needed by get_photo_data

                new_log = Log.objects.latest("id")
                GPIO.output(26, GPIO.HIGH)
                data = face_detect.get_photo_data(new_log.id)
                GPIO.output(26, GPIO.LOW)
                new_log.age = data["age"]
                new_log.sex = data["sex"]
                new_log.photo = data["photo"]
                new_log.save()

                message = 'Welcome!'
                description = 'You have {} accesses left. ' \
                              'The card will expire on {}'.format(card.remaining_accesses,
                                                                  card.expiration_date)
                # TODO implement printing messages on LCD display and red/green led
                #  see http://www.circuitbasics.com/raspberry-pi-lcd-set-up-and-programming-in-python/
                # lcd.write_string(u'Welcome\n\r{} remaining'.format(card.remaining_accesses))
                # time.sleep(3)
                # lcd.clear()
            elif card.remaining_accesses == 0:
                GPIO.output(17, GPIO.HIGH)
                message = 'No accesses'
                description = 'You have no more accesses remained. ' \
                              'Please recharge your card at the reception'
                # lcd.write_string(u'No accesses\n\rPlease recharge')
                # time.sleep(3)
                # lcd.clear()
            else:
                GPIO.output(17, GPIO.HIGH)
                message = 'Card expired'

rfid/templates/rfid/about.html
{% extends 'base_site.html' %}

{% block title %}About{% endblock %}

{% block content %}

    <h1>Coming soon...</h1>
    <p>
        This page is under construction. <br/>In the meantime you can take a look at the source code of the website
        <a href="https://github.com/LorenzoAgnolucci/smartaccess" class="text-primary">here</a>.
    </p>

    <div class="container">
        <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSHhxzaw54qZQlRqYt0gzNCq7jvY5YFysMtnNS8_zYVJ4dvPoOW28_ld0fvWwgTOuzo4Zd3u70goLvS/embed?start=false&loop=false&delayms=3000"
                frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true"
                webkitallowfullscreen="true"></iframe>
    </div>


    {#    TODO fill the about page #}

{% endblock %}

rfid/templates/rfid/access_main.html
{% extends 'base_site.html' %}

{% block title %}Access Page{% endblock %}

{% block extra-script %}

    <script type="text/javascript">
        function Redirect() {
            window.location = "{% url 'rfid:access_result' %}";
        }
        setTimeout('Redirect()', 1000);
    </script>

{% endblock %}


{% block content %}

    <h1>Access</h1>

    <p>Scan your card...</p>

    <p>Page should redirect to card scanning.<br>
        If not working <a class="text-primary" href="{% url 'rfid:access_result' %}">click here</a></p>

    <a class="btn btn-primary" href="{% url 'login' %}">Log in</a>

{% endblock %}

rfid/templates/rfid/access_result.html
{% extends 'base_site.html' %}

{% block title %}Access Page{% endblock %}

{% block extra-script %}

    <script type="text/javascript">
        function Redirect() {
            window.location="{% url 'rfid:access_main' %}";
        }
        setTimeout('Redirect()', 10000);
    </script>

{% endblock %}


{% block content %}

    <h1>Access</h1>

    <h2>{{ message }}</h2>

    <p>{{ description }}</p>

    <p>Page should reload main access page in 3 seconds, otherwise <a href="{% url 'rfid:access_main' %}">click here.</a></p>

    <a class="text-primary" href="{% url 'login' %}">Log in</a>

{% endblock %}

rfid/templates/rfid/add_card.html
{% extends 'base_site.html' %}

{% block title %}Add Card{% endblock %}

{% block content %}

    <h1>Add Card</h1>

    <p>Scan the card...</p>

{% endblock %}

rfid/templates/rfid/add_card_fail.html
{% extends 'base_site.html' %}

{% block title %}Add Card{% endblock %}

{% block content %}

    <h1>Card already in the database</h1>
    <p>The card {{ card_id }} is already in the database. If you meant to update the expiring date or the remaining
        accesses, please hit the button below</p>
    <a class="btn btn-primary" href="{% url 'rfid:write_card' %}" role="button">Write</a>

{% endblock %}

rfid/templates/rfid/add_card_success.html
{% extends 'base_site.html' %}

{% block title %}Add Card{% endblock %}

{% block content %}

    <h1>Added new card!</h1>
    <p>The card {{ card_id }} is now in the database. Click the button below if you want to edit the expiration date and
        add new accesses</p>
    <a class="btn btn-primary" href="{% url 'rfid:write_card' %}" role="button">Write</a>

{% endblock %}

rfid/templates/rfid/dashboard.html
{% extends 'base_site.html' %}

{% block extra-script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages': ['corechart', 'controls']});
        google.charts.setOnLoadCallback(drawDashboard);

        function drawDashboard() {

            var djangoData = {{ array|safe }};
            var data = google.visualization.arrayToDataTable(djangoData);

            drawChart(data);

            var hourFilter = new google.visualization.ControlWrapper({
                controlType: 'NumberRangeFilter',
                containerId: 'filter_hour_div',
                dataTable: data,
                options: {
                    filterColumnIndex: 1
                }
            });

            google.visualization.events.addListener(hourFilter, 'statechange', stateChangeHandler);

            hourFilter.draw();

            var sexFilter = new google.visualization.ControlWrapper({
                controlType: 'CategoryFilter',
                containerId: 'filter_sex_div',
                dataTable: data,
                options: {
                    filterColumnIndex: 2,
                    ui: {
                        allowMultiple: true,
                        allowTyping: true,
                        caption: 'Choose sex'
                    }

                }
            });

            google.visualization.events.addListener(sexFilter, 'statechange', stateChangeHandler);

            sexFilter.draw();

            var ageFilter = new google.visualization.ControlWrapper({
                controlType: 'NumberRangeFilter',
                containerId: 'filter_age_div',
                dataTable: data,
                options: {
                    filterColumnIndex: 3
                }
            });

            google.visualization.events.addListener(ageFilter, 'statechange', stateChangeHandler);

            ageFilter.draw();

            function drawChart(dataTable) {
                var dataGroup = google.visualization.data.group(
                    dataTable,
                    [0],
                    [{column: 1, aggregation: google.visualization.data.count, type: 'number', label: 'Count'}]
                );

                var sortedData = sortByDayOfTheWeek(dataGroup);

                var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
                chart.draw(sortedData, {
                    'width': 1000,
                    'height': 500,
                    'legend': 'right',
                    'title': 'Number of accesses'
                });
            }

            function stateChangeHandler() {
                var sexSelection = sexFilter.getState();
                var hourRange = hourFilter.getState();
                var ageRange = ageFilter.getState();
                var view = new google.visualization.DataView(data);
                view.setRows(data.getFilteredRows([
                    {
                        column: 1,
                        minValue: hourRange.lowValue,
                        maxValue: hourRange.highValue
                    },
                    {
                        column: 2,
                        test: function (value) {
                            return sexSelection.selectedValues.includes(value) ||
                                sexSelection.selectedValues.length === 0
                        }
                    },
                    {
                        column: 3,
                        minValue: ageRange.lowValue,
                        maxValue: ageRange.highValue
                    }
                ]));
                drawChart(view);
            }

            function sortByDayOfTheWeek(dataTable) {
                var order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
                var sortedDataTable = new google.visualization.arrayToDataTable([[{label: "Day", type: "string"},
                                                                                {label: "Count", type: "number"}]]);

                for (var i = 0; i < order.length; i++) {
                  for (var j = 0; j < dataTable.getNumberOfRows(); j++){
                      if (dataTable.getValue(j, 0) === order[i]) {
                      sortedDataTable.addRow([order[i], dataTable.getValue(j, 1)]);
                      }
                  }
                }
                return sortedDataTable;
            }
        }
    </script>
{% endblock %}

{% block title %}Dashboard{% endblock %}

{% block outer %}
    <div class="container-fluid justify-content-center">
        <h1 class="text-center">Dashboard</h1>
        <div id="dashboard_div" class="row mx-auto">
            <div id="chart_div" class="col-md-8"></div>
            <div class="col-sm-3 align-self-center">
                <div id="filter_age_div" class="row"></div>
                <div id="filter_hour_div" class="row"></div>
                <div id="filter_sex_div" class="row"></div>
            </div>
        </div>
    </div>
{% endblock %}

rfid/templates/rfid/delete_card.html
{% extends 'base_site.html' %}

{% block title %}Delete Card{% endblock %}

{% block content %}

    <h1>Card info</h1>

    <table class="table">
        <tbody>
        <tr>
            <th scope="row">Card No</th>
            <td>{{ card_id }}</td>
        </tr>
        <tr>
            <th scope="row">Rem. accesses</th>
            <td>{{ remaining_accesses }}</td>
        </tr>
        <tr>
            <th scope="row">Exp. date</th>
            <td>{{ expiration_date }}</td>
        </tr>
        </tbody>
    </table>

    {# empty form with only the submit button #}
    <form action="{% url 'rfid:delete_card' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-danger"
                type="submit"
                value="Delete"
                onclick="return confirm('Are you sure?')">Delete</button>
    </form>

{% endblock %}

rfid/templates/rfid/delete_card_scan.html
{% extends 'base_site.html' %}

{% block title %}Delete Card{% endblock %}

{% block content %}

    <h1>Delete a card</h1>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <p>Click the button to scan the card you want to delete from the database</p>
    <div class="alert alert-warning">WARNING! All relative data will be lost forever (logs, photos, statistics...)
    </div>
    <a class="btn btn-primary" href="{% url 'rfid:delete_card' %}" role="button">Scan</a>
    <p class="small">Don't worry, you will confirm it after the scanning</p>
{% endblock %}

rfid/templates/rfid/index.html
{% extends 'base_site.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <h1>Homepage</h1>
    {% if user.is_authenticated %}
        {# BOOTSTRAP CARDS #}
        <div class="row">
            <div class="col-sm-4 py-2" style="max-width: 18rem;">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Write</h5>
                        <p class="card-text">Write data on an existing card.</p>
                        <a href="{% url 'rfid:write_card_scan' %}" class="btn btn-primary mt-auto">Go</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 py-2" style="max-width: 18rem;">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Add</h5>
                        <p class="card-text">Add card to the database</p>
                        <a href="{% url 'rfid:add_card_scan' %}" class="btn btn-primary mt-auto">Go</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 py-2" style="max-width: 18rem;">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Delete</h5>
                        <p class="card-text">Remove a card from the database</p>
                        <a href="{% url 'rfid:delete_card_scan' %}" class="btn btn-primary mt-auto">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-4 py-2" style="max-width: 18rem;">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Dashboard</h5>
                        <p class="card-text">Visualize statistics on the data</p>
                        <a href="{% url 'rfid:dashboard' %}" class="btn btn-primary mt-auto">Go</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 py-2" style="max-width: 18rem;">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Logs</h5>
                        <p class="card-text">See all the logs</p>
                        <a href="{% url 'rfid:logs' %}" class="btn btn-primary mt-auto">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    {% endif %}
    <div class="row">
        <div class="col-sm-4 py-2" style="max-width: 18rem;">
            <div class="card h-100">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Access</h5>
                    <p class="card-text">Client access page</p>
                    <a href="{% url 'rfid:access_main' %}" class="btn btn-primary mt-auto">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4 py-2" style="max-width: 18rem;">
            <div class="card h-100">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Info</h5>
                    <p class="card-text">Get card info</p>
                    <a href="{% url 'rfid:info_card_scan' %}" class="btn btn-primary mt-auto">Go</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

rfid/templates/rfid/info_card.html
{% extends 'base_site.html' %}

{% block title %}Info Card{% endblock %}

{% block content %}
    <div class="col-sm-8">

        <h2>Info card {{ card_id }}</h2>

        {% if messages %}

            {% for message in messages %}
                <div class="alert {{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}

        {% else %}
            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">Card No</th>
                    <td>{{ card_id }}</td>
                </tr>
                <tr>
                    <th scope="row">Rem. accesses</th>
                    <td>{{ remaining_accesses }}</td>
                </tr>
                <tr>
                    <th scope="row">Exp. date</th>
                    <td>{{ expiration_date }}</td>
                </tr>
                </tbody>
            </table>
        {% endif %}
            <a class="btn btn-primary" href="{% url 'rfid:info_card_scan' %}" role="button">Go back</a>
    </div>


{% endblock %}

rfid/templates/rfid/write_card.html
{% extends 'base_site.html' %}

{% block title %}Write Card{% endblock %}

{% load crispy_forms_tags %}

{% block extra-script %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $( function() {
    $( "#datepicker" ).datepicker({
        dateFormat: "yy-mm-dd"
    });

    } );
    </script>
{% endblock %}

{% block content %}

    <h1>Write card</h1>
    <p>Change the expiration date and/or add more accesses to the scanned card</p>

    <form action="{% url 'rfid:write_card' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>

{% endblock %}

rfid/templates/rfid/write_card_add_new.html
{% extends 'base_site.html' %}

{% block title %}Write Card | Add{% endblock %}

{% block content %}

    <p>The card {{ card_id }} is not in the database, would you like to add it?</p>
    <a class="btn btn-primary" href="{% url 'rfid:add_card' %}" role="button">Yes</a>
    <a class="btn btn-secondary" href="{% url 'rfid:index' %}" role="button">No</a>

{% endblock %}