rfid/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import views

app_name = 'rfid'
urlpatterns = [
                  path('', views.IndexView.as_view(), name='index'),

                  path('add_card/', views.add_card, name='add_card'),
                  path('add_card_scan/', views.AddCardScanView.as_view(), name='add_card_scan'),

                  path('write_card/', views.write_card, name='write_card'),
                  path('write_card_scan/', views.WriteCardScanView.as_view(), name='write_card_scan'),

                  path('info_card/', views.info_card, name='info_card'),
                  path('info_card_scan/', views.InfoCardScanView.as_view(), name='info_card_scan'),

                  path('delete_card/', views.delete_card, name='delete_card'),
                  path('delete_card_scan/', views.DeleteCardScanView.as_view(), name='delete_card_scan'),

                  path('dashboard/', views.dashboard, name='dashboard'),
                  path('logs', views.logs, name='logs'),

                  path('about/', views.AboutView.as_view(), name='about'),

                  path('access/', views.AccessMainView.as_view(), name='access_main'),
                  path('access/result/', views.access_result, name='access_result'),
                  path('access/result/<int:card_id>/', views.access_result, name='access_result'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartaccess/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('rfid/', include('rfid.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='rfid/'), name='index_redir'),

]

templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'rfid/css/bootstrap.min.css' %}">
    <script src="{% static 'rfid/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'rfid/js/popper.min.js' %}"></script>
    <script src="{% static 'rfid/js/bootstrap.min.js' %}"></script>
    <!-- Material Design Bootstrap -->
    <link href="{% static 'rfid/css/mdb.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'rfid/mystyle.css' %}" media="screen"/>

    <title>{% block title %}Home{% endblock %} | Smart Access</title>

    {% block extra-script %}
    {% endblock %}

</head>

<body class="h-100">

{% block nav %}
{% endblock %}

<div class="container h-100 pt-3 mw-100">
    <div class="row justify-content-center mt-auto">
        {% block outer %}
            <div class="col-lg-8">
                {% block content %}
                {% endblock %}
            </div>
        {% endblock %}
    </div>
</div>
    <!-- Footer -->
    <footer id="sticky-footer" class="page-footer font-small" style="background-color: #4285F4">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 bottom">© 2019 Website under GPL:
            <a href="https://www.gnu.org/licenses/gpl-3.0.en.html">GNU General Public Licence</a>
        </div>
        <!-- Copyright -->

    </footer>
</body>
</html>

templates/base_site.html
{% extends 'base.html' %}

{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark primary-color">
        <a class="navbar-brand" href="{% url 'rfid:index' %}">SmartAccess</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rfid:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rfid:access_main' %}">Access</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Management
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'rfid:write_card_scan' %}">Write Card</a>
                        <a class="dropdown-item" href="{% url 'rfid:add_card_scan' %}">Add Card</a>
                        <a class="dropdown-item" href="{% url 'rfid:info_card_scan' %}">Card Info</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'rfid:delete_card_scan' %}">Delete Card</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Statistics
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'rfid:dashboard' %}">Dashboard</a>
                        <a class="dropdown-item" href="{% url 'rfid:logs' %}">Logs</a>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rfid:about' %}">About</a>
                </li>
            </ul>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hi {{ user.username }}, </span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}